import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import StoreProvider from './providers/StoreProvider';
import ToastProvider from './providers/ToastProvider';
import { ReactQueryClientProvider } from './providers/ReactQueryClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <StoreProvider>
        <html lang="en">
          <body className={inter.className}>
            <ToastProvider>{children}</ToastProvider>
          </body>
        </html>
      </StoreProvider>
    </ReactQueryClientProvider>
  );
}
